### ISSUE TITLE
uibar button item

### ISSUE THREAD

**Issue by nikhil191090** [bismasaeed00/BSDropDown#3]
how to use this for uibarbutton item??

**Comment by bismasaeed00** [comment]
You are using it in navigation bar?

**Comment by bismasaeed00** [comment]
if your navigation bar is covering the list, you can use this after adding it to subview.
`self.navigationController.navigationBar.layer.zPosition = -1;`

If you have problem with position of the view, then you need to calculate it's origin point manually according to your needs.

**Comment by nikhil191090** [comment]
yes i am using it in navigation bar
